<?php
	include "../middlewares/isAuthenticated.php";
	include "../middlewares/isAdminOrStaff.php";
	include_once "../db/connection.php";

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sales report</title>

    <style>
    .brand {
        margin-top: 30px;
        margin-bottom: 30px;
    }

    .container {
        width: 100%;
        height: auto;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        margin-bottom: 10px;
    }

    h3 {
        margin-bottom: 10px;
    }
    </style>
    <link rel="stylesheet" href="/bookmart/public/css/index.css">
</head>

<body>
    <div class="container">
        <img class="brand" src="/bookmart/public/images/brand.svg" />
        <h3>Report Type : Sales report</h3>
        <h3>Generated By : <?=$_SESSION['username']?></h3>
        <?php if (isset($_GET['from'])): ?>
        <h3>From: <?=$_GET['from']?></h3>
        <h3>To: <?=$_GET['to']?></h3>
        <?php endif?>
    </div>

    <div class="table-wrapper">
        <div class="table">
            <div class="header row">
                <div class="cell">No</div>
                <div class="cell">Total Amount</div>
                <div class="cell">Order Date</div>
                <div class="cell">No of items</div>
                <div class="cell">Status</div>
            </div>
            <?php
            	if (isset($_GET['all'])) {
            		$stmt = $pdo->query("SELECT Order_id,O_date,O_status,total_amt,tbl_Order.Cart_master_id,COUNT(Item_id) as no_of_items FROM tbl_order LEFT JOIN tbl_cart_master ON tbl_Order.Cart_master_id=tbl_cart_master.Cart_master_id LEFT JOIN tbl_cart_child ON tbl_Order.Cart_master_id=tbl_cart_child.Cart_master_id GROUP BY Cart_master_id ORDER BY O_date ASC;");
            	} else {
            		$stmt = $pdo->prepare("SELECT Order_id,O_date,O_status,total_amt,tbl_Order.Cart_master_id,COUNT(Item_id) as no_of_items FROM tbl_order LEFT JOIN tbl_cart_master ON tbl_Order.Cart_master_id=tbl_cart_master.Cart_master_id LEFT JOIN tbl_cart_child ON tbl_Order.Cart_master_id=tbl_cart_child.Cart_master_id GROUP BY Cart_master_id HAVING O_date>=? AND O_date<=? ORDER BY O_date ASC");
            		$stmt->execute([$_GET['from'], $_GET['to']]);
            	}
            	$i = 0;
            	while ($row = $stmt->fetch(PDO::FETCH_ASSOC)):
            ?>
            <div class="row">
                <div class="cell" data-title="No"><?=++$i?></div>
                <div class="cell" data-title="Total Amount"><?=htmlspecialchars($row['total_amt'])?></div>
                <div class="cell" data-title="Order date"><?=htmlspecialchars($row['O_date'])?></div>
                <div class="cell" data-title="No of items"><?=htmlspecialchars($row['no_of_items'])?></div>
                <div class="cell" data-title="Status"><?=htmlspecialchars($row['O_status'])?></div>
            </div>
            <?php endwhile?>
        </div>
    </div>
</body>

</html>

<script>
const h3 = document.createElement('h3');
h3.innerHTML = `Generated At : ${new Date()}`;
document.querySelector('.container').appendChild(h3);
print();
</script>