<?php
	include "../middlewares/isAuthenticated.php";
	include "../middlewares/isAdminOrStaff.php";
	include_once "../db/connection.php";

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Staff report</title>


    <link rel="stylesheet" href="/bookmart/public/css/index.css">
    <style>
    .brand {
        margin-top: 30px;
        margin-bottom: 30px;
    }

    .container {
        width: 100%;
        height: auto;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        margin-bottom: 10px;
    }

    h3 {
        margin-bottom: 10px;
    }

    .cell {
        font-size: 15px;
        white-space: normal;
    }
    </style>
</head>

<body>
    <div class="container">
        <img class="brand" src="/bookmart/public/images/brand.svg" />
        <h3>Report Type : Customer report</h3>
        <h3>Generated By : <?=$_SESSION['username']?></h3>
        <?php if (isset($_GET['from'])): ?>
        <h3>From: <?=$_GET['from']?></h3>
        <h3>To: <?=$_GET['to']?></h3>
        <?php endif?>
    </div>

    <div class="table-wrapper">
        <div class="table">
            <div class="header row">
                <div class="cell">No</div>
                <div class="cell">Firstname</div>
                <div class="cell">Lastname</div>
                <div class="cell">House name</div>
                <div class="cell">City</div>
                <div class="cell">District</div>
                <div class="cell">Pincode</div>
                <div class="cell">Phone</div>
                <div class="cell">Email</div>
                <div class="cell">Joining date</div>
                <div class="cell">Status</div>
            </div>
            <?php
            	if (isset($_GET['all'])) {
            		$stmt = $pdo->query("SELECT tbl_Login.Username,User_status,Cust_id,C_fname,C_lname,C_city,C_district,C_housename,C_pin,C_phno,added_date FROM tbl_Login LEFT JOIN tbl_Customer ON tbl_Login.Username = tbl_Customer.Username WHERE User_type='customer' ORDER BY added_date ASC;");
            	} else {
            		$stmt = $pdo->prepare("SELECT tbl_Login.Username,User_status,Cust_id,C_fname,C_lname,C_city,C_district,C_housename,C_pin,C_phno,added_date FROM tbl_Login LEFT JOIN tbl_Customer ON tbl_Login.Username = tbl_Customer.Username WHERE User_type='customer' AND  added_date BETWEEN ? AND ? ORDER BY added_date ASC;");
            		$stmt->execute([$_GET['from'], $_GET['to']]);
            	}
            	$i = 0;
            	while ($row = $stmt->fetch(PDO::FETCH_ASSOC)):
            ?>
            <div class="row">
                <div class="cell" data-title="No"><?=++$i?></div>
                <div class="cell" data-title="Firstname"><?=$row['C_fname'] ? htmlspecialchars($row['C_fname']) : "Not provided"?></div>
                <div class="cell" data-title="Lastname"><?=$row['C_lname'] ? htmlspecialchars($row['C_lname']) : "Not provided"?></div>
                <div class="cell" data-title="housename"><?=$row['C_housename'] ? htmlspecialchars($row['C_housename']) : "Not provided"?></div>
                <div class="cell" data-title="City"><?=$row['C_city'] ? htmlspecialchars($row['C_city']) : "Not provided"?></div>
                <div class="cell" data-title="District"><?=$row['C_district'] ? htmlspecialchars($row['C_district']) : "Not provided"?></div>
                <div class="cell" data-title="Pincode"><?=$row['C_pin'] ? htmlspecialchars($row['C_pin']) : "Not provided"?></div>
                <div class="cell" data-title="Phone number"><?=$row['C_phno'] ? htmlspecialchars($row['C_phno']) : "Not provided"?></div>
                <div class="cell" data-title="Email"><?=htmlspecialchars($row['Username'])?></div>
                <div class="cell" data-title="Email"><?=htmlspecialchars($row['added_date'])?></div>
                <div class="cell" data-title="Email"><?=htmlspecialchars($row['User_status'])?></div>
            </div>
            <?php endwhile?>
        </div>
    </div>
</body>

</html>

<script>
const h3 = document.createElement('h3');
h3.innerHTML = `Generated At : ${new Date()}`;
document.querySelector('.container').appendChild(h3);
print();
</script>