<?php
	include "../middlewares/isAuthenticated.php";
	include "../middlewares/isAdminOrStaff.php";
	include_once "../db/connection.php";

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Purchase report</title>

    <style>
    .brand {
        margin-top: 30px;
        margin-bottom: 30px;
    }

    .container {
        width: 100%;
        height: auto;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        margin-bottom: 10px;
    }

    h3 {
        margin-bottom: 10px;
    }
    </style>
    <link rel="stylesheet" href="/bookmart/public/css/index.css">
</head>

<body>
    <div class="container">
        <img class="brand" src="/bookmart/public/images/brand.svg" />
        <h3>Report Type : Purchase report</h3>
        <h3>Generated By : <?=$_SESSION['username']?></h3>
        <?php if (isset($_GET['from'])): ?>
        <h3>From: <?=$_GET['from']?></h3>
        <h3>To: <?=$_GET['to']?></h3>
        <?php endif?>
    </div>

    <div class="table-wrapper">
        <div class="table">
            <div class="header row">
                <div class="cell">No</div>
                <div class="cell">Vendor</div>
                <div class="cell">Total Amount</div>
                <div class="cell">Purchase Date</div>
                <div class="cell">Purchased By</div>
                <div class="cell">Status</div>
            </div>
            <?php
            	if (isset($_GET['all'])) {
            		$stmt = $pdo->query("SELECT Purchase_master_id,V_name,Purchase_date,COALESCE(S_fname,'admin') AS Purchased_by,Total_amt,Status FROM tbl_Purchase_master LEFT JOIN tbl_Staff ON Purchased_by = Username JOIN tbl_Vendor ON tbl_Purchase_master.Vendor_id = tbl_Vendor.V_id ORDER BY Purchase_date ASC");
            	} else {
            		$stmt = $pdo->prepare("SELECT Purchase_master_id,V_name,Purchase_date,COALESCE(S_fname,'admin') AS Purchased_by,Total_amt,Status  FROM tbl_Purchase_master LEFT JOIN tbl_Staff ON Purchased_by = Username JOIN tbl_Vendor ON tbl_Purchase_master.Vendor_id = tbl_Vendor.V_id HAVING Purchase_date>=? AND Purchase_date<=? ORDER BY Purchase_date ASC;");
            		$stmt->execute([$_GET['from'], $_GET['to']]);
            	}
            	$i = 0;
            	while ($row = $stmt->fetch(PDO::FETCH_ASSOC)):
            ?>
            <div class="row">
                <div class="cell" data-title="No"><?=++$i?></div>
                <div class="cell" data-title="vendor"><?=htmlspecialchars($row['V_name'])?></div>
                <div class="cell" data-title="Total Amount"><?=htmlspecialchars($row['Total_amt'])?></div>
                <div class="cell" data-title="Purchase Date"><?=htmlspecialchars($row['Purchase_date'])?></div>
                <div class="cell" data-title="Purchased By"><?php echo $row['Purchased_by'] ?></div>
                <div class="cell" data-title="Status"><?php echo $row['Status'] ?></div>
            </div>
            <?php endwhile?>
        </div>
    </div>
</body>

</html>

<script>
const h3 = document.createElement('h3');
h3.innerHTML = `Generated At : ${new Date()}`;
document.querySelector('.container').appendChild(h3);
print();
</script>